import "./navigation/navigation.ts";
import "./profile-all/profile-all.ts";
import "./category/category.ts";
import "./horizon-image/horizon-image.ts";
import "./receipe-paper/receipe-paper.ts";
import "./review-choice/review-choice.ts";
import "./footer/footer.ts";
import "./theme/theme.ts";
import "./reservation";
import "./visit-record";
import "./feed";
import "./order-page/order-table.ts"