import "./location/location.ts";
import "./navigation/navigation.ts";
import "./post/post.ts";
import "./post-list/post-list.ts";
import "./profile-all/profile-all.ts";
import "./theme-bar/theme-bar.ts";
import "./category/category.ts";
import "./horizon-image/horizon-image.ts";
import "./receipe-paper/receipe-paper.ts";
import "./reservation/reservation-toggle.ts";
import "./reservation/reservation-types.ts";
import "./reservation/reservation-visit-list.ts";
import "./review-choice/review-choice.ts";
import "./theme/theme.ts";
import "./visit-record/visit-record-noreview.ts";
import "./visit-record/visit-record-complete.ts";
import "./theme-enroll/theme-enroll.ts"
import "./review-post/review-post.ts"
import "./review-plus/review-plus.ts"

